### ISSUE TITLE
Test failed: `wrts lists should get lists`

### ISSUE THREAD

**Issue by StephanMeijer** [simplyGits/wrts#2]
`mocha test/test.js`

```
  wrts
    ✓ should login
    ✓ should get user info (628ms)
    lists
      1) should get lists
    schools
      ✓ should get schools (98ms)
    tests
      ✓ should get test results (154ms)


  4 passing (3s)
  1 failing

  1) wrts lists should get lists:
     Uncaught TypeError: Object function Object() { [native code] } has no method 'setPrototypeOf'
      at module.exports.List.parse (lib/list.js:68:10)
      at Array.map (native)
      at lib/index.js:102:19
      at Request._callback (lib/utils.js:35:5)
      at Request.self.callback (node_modules/request/request.js:200:22)
      at Request.<anonymous> (node_modules/request/request.js:1067:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:988:12)
      at _stream_readable.js:920:1
```

**Comment by lieuwex** [comment]
Seems like `setPrototypeOf` is only available in es6 environments, I will push a commit that falls back to `__proto__` for older environments. But I would still update your Node.js. ;)

**Comment by lieuwex** [comment]
I think I take that back, keeping backwards compat with something we didn't even support in the first place seems a bit useless when the current node version supports the features. 

cc: @simplyGits/simplycoders Thoughts?

**Comment by tomsmeding** [comment]
If you don't support it, then explicitly [don't support it](https://docs.npmjs.com/files/package.json#engines), and you're fine I think.

**Comment by StephanMeijer** [comment]
I agree with @tomsmeding. I will update my NodeJS installation, but I think it's a good idea to explicitly mark non-supported versions (or mark only the supported ones).

**Comment by lieuwex** [comment]
I have no idea which version supported `setPrototypeOf` first.

**Comment by lieuwex** [comment]
`>0.12` it seems
